### ISSUE TITLE
Some info about Tesseract-OCR v4 and lstm

### ISSUE THREAD

**Issue by Subarashii-no-Fansub** [Jocker666z/ffmes#2]
Hello

I don't know if you're aware but using option **18** of this script and last version of tesseract, it takes more time than the v3

LSTM takes more time but is more reliable

If some want to use legacy version, you need to add `--oem 0` to the tesseract command

**Comment by Jocker666z** [comment]
Thanks for the info, I am in the process of testing to implement the choice.

**Comment by Jocker666z** [comment]
0.57 implement the choice ->
https://github.com/Jocker666z/ffmes/commit/eb92f1643f83f393630816063fba76bfb4dc159b

**Comment by Jocker666z** [comment]
Done https://github.com/Jocker666z/ffmes/commit/eb92f1643f83f393630816063fba76bfb4dc159b
