### ISSUE TITLE
Batch sub to srt?

### ISSUE THREAD

**Issue by Extarys** [Jocker666z/ffmes#3]
I have a folder with multiple sub/idx files.
Is there a way to auto select option 18/0 (eng)/1 (slow) ? I could loop for each file but I'm not sure how I can pre select those settings from the command line.

Thanks for this btw - it's magic! :heart:

**Comment by Extarys** [comment]
:man_facepalming: Nevermind... I just point the thing to my first .sub file and it take care of the rest.

:laughing:

**Comment by JSubelj** [comment]
Hi, I have a problem with batch converting. If I point ffmes to file .sub file `ffmes -i subs.sub` I get `[!] "subs.sub" is not supported.` error. Same if I point it to the .idx file. Is there still a way to convert without command line menu. (I know about -s flag, but then I still need to select 0 (eng)/1 (slow).

Thanks in advance and great work! Will definitely use this tool for a lot of things :)

**Comment by Jocker666z** [comment]
> 

Hi, it's true that it's been a while since I've seen this option, I'm looking at it in the evening (Western Europe here).

**Comment by Jocker666z** [comment]
> Hi, I have a problem with batch converting. If I point ffmes to file .sub file `ffmes -i subs.sub` I get `[!] "subs.sub" is not supported.` error. Same if I point it to the .idx file. Is there still a way to convert without command line menu. (I know about -s flag, but then I still need to select 0 (eng)/1 (slow).
> 
> Thanks in advance and great work! Will definitely use this tool for a lot of things :)

While waiting for a modification the bypass is this one:
* put the sub/idx files in a directory
* run ffmes in this directory without arguments

**Comment by Jocker666z** [comment]
Now accept idx as input https://github.com/Jocker666z/ffmes/commit/f4a77fa7ba0e66236b914c1396aa7c02f8fbc079

So I will also improve and correct several bugs in the srt conversion
