### ISSUE TITLE
Possibility to convert PGS Subtitles instead of VOBSUB

### ISSUE THREAD

**Issue by TheLux83** [Jocker666z/ffmes#4]
Hey there,

I've learned about your script from [subarashii-no-fansub's Subbing Tutorial](https://subarashii-no-fansub.github.io/Subbing-Tutorial/Convert-vobsub-file-into-srt/) and I think it's a really handy script. 
But there is one thing, I would like to know, if it is possible.
Since every bluray I have has HDMV/PGS subtitles and your script only supports VOBSUB subtitles, I have to convert every subtitle prior to OCR'ing it with your script.
Do you see a possibility to integrate PGS subtitle support into your script?

It's not that bad if I convert one movie, but if I convert my Game of Thrones collection, I end up with around 256 subtitles (8 seasons, around 8'ish episodes, englisch & german subtitles + forced subtitles). I have to convert to VOBSUB and the only really handy tool I've found was BDsup2sub++ which cannot do batch conversion.

Really thank you for this script! :-)

**Comment by Jocker666z** [comment]
If I understand correctly you want to convert the HDMV/PGS bluray subtitle format (.sup) to .srt? Is that it?

**Comment by Jocker666z** [comment]
If that's the case, there is apparently nothing that can be properly integrated into ffmes.
You should rather look at this sides:

- https://www.nikse.dk/subtitleedit/help#batchconvert
- https://github.com/PimvanderLoos/pgs2srt (to integrate in a script to make batches)

If you can't find a solution, let me know. When I have more time, I'll try to do something with the python script outside of ffmes.

**Comment by TheLux83** [comment]
> If I understand correctly you want to convert the HDMV/PGS bluray subtitle format (.sup) to .srt? Is that it?

Yep. I wanted to OCR through my PGS files. I already tried SubtitleEdit and it's a pretty cool app, but unfortunately it hangs itself when I try to use it with Linux.
The other repo looks promising. I'll have a look into it and try to get something running.

Also, I'm not really good with python (beginner level at least), but maybe I can be of a little help, if you're trying to figure something out.

But first I'll try the pgs2srt repo. Thanks for the suggestions :-)

**Comment by Jocker666z** [comment]
> > If I understand correctly you want to convert the HDMV/PGS bluray subtitle format (.sup) to .srt? Is that it?
> 
> Yep. I wanted to OCR through my PGS files. I already tried SubtitleEdit and it's a pretty cool app, but unfortunately it hangs itself when I try to use it with Linux. The other repo looks promising. I'll have a look into it and try to get something running.
> 
> Also, I'm not really good with python (beginner level at least), but maybe I can be of a little help, if you're trying to figure something out.
> 
> But first I'll try the pgs2srt repo. Thanks for the suggestions :-)
> 
> I'll let you know if I got something to work :-)

After some quick tests, the solution seems to me to be this > https://github.com/ratoaq2/pgsrip
