### ISSUE TITLE
Converting Chinese Simplified idx/sub to srt just creates a 0 byte file

### ISSUE THREAD

**Issue by glu8716** [Jocker666z/ffmes#5]
As the title says I'm trying to convert a Chinese Simplified idx/sub to srt. I can see the .tif frames being extracted correctly, but when it comes to the srt conversion only a 0 byte blank files is created. This is happening with both "fast" and "reliable" method.

**Comment by Jocker666z** [comment]
Can you send me the concerned idx/sub files?

**Comment by glu8716** [comment]
Sure. 
[红楼梦.1987.S01E24.480p.DVD-REMUX.sub.tar.gz](https://github.com/Jocker666z/ffmes/files/10823144/1987.S01E24.480p.DVD-REMUX.sub.tar.gz)

**Comment by Jocker666z** [comment]
I have partially fix, options 0 & 2 should work.

For Chinese, tesseract seems to need a training file, I'll fix that later.

I saw, that I have other things to correct :)

**Comment by Jocker666z** [comment]
I've cleaned all this up, it should work.

Let me know if everything is ok

**Comment by glu8716** [comment]
Thank you, I can confirm that the script works now. 
However, I'm getting really bad results. Out of 640 text files that are generated, the converted srt only has 60 lines of text. A lot are missing. And the accuracy of the text is really bad too, there are a lot of errors. I don't know if this is due to some bug or to the tesseract data. Considering the english one works almost flawlessy, I find it strange that the chinese one is so bad...

**Comment by Jocker666z** [comment]
> tesseract

I have improved (I think) the command of tesseract, I will need your opinion (my level in Chinese language is equivalent to zero).

It seems to me that some spaces are missing.

**Comment by glu8716** [comment]
Thanks again for the prompt reply, this seems to be working almost flawlessly now! There are still some characters that are not recognized, like 哎, which is wrongly OCRed as 或 or呆 in the sub I provided. Sometimes there are also some lines that are generated out of nothing (line not present in the original sub) with gibberish characters.
As for the lack of spaces, it's normal, as chinese doesn't have spaces.

**Comment by Jocker666z** [comment]
Okay, I don't think I can better that.

If you have any other problems or requests, please feel free to open another issue.
