### ISSUE TITLE
Support for IDX/SUB containing multiple languages

### ISSUE THREAD

**Issue by glu8716** [Jocker666z/ffmes#6]
I have a bunch of IDX/SUB files that contain three languages: traditional and simplified chinese and english. I'd like to OCR all the english ones at once with ffmes, but ffmes doesn't seem to be able to detect multiple languages and in the end it only converts the first one which is traditional chinese.
Here's a screen from SubtitleRip who can detect which language to load:
![2023-07-10_01-34](https://github.com/Jocker666z/ffmes/assets/33501455/b3bdede2-38cb-4c20-b403-d1ea82f4b35b)

I'll also leave a sample if needed for testing.
https://anonfiles.com/j74eqa16zd/The_New_Heaven_Sword_Dragon_Sabre_Ep_1_sub_tar_gz

**Comment by Jocker666z** [comment]
ffmes doesn't have the multiple language feature (mixed).

I leave this issue open for now, I'll add this feature in a near future. Thanks for have report this case.

**Comment by glu8716** [comment]
I tried to delete the chinese language from the .idx file so that by keeping only English I can OCR it through ffmes. That's how my .idx file looks like:

```
# Language index in use
langidx: 2

# English
id: en, index: 2
# Decomment next line to activate alternative name in DirectVobSub / Windows Media Player 6.x
# alt: en
# Vob/Cell ID: 1, 1 (PTS: 0)
timestamp: 00:00:00:166, filepos: 000000000
timestamp: 00:00:03:870, filepos: 000001000
[...]
```
While SubtitleEdit now directly loads English subtitles and can OCR fine, ffmes seems to fail to OCR. The process takes only 1 second and the result is a 0 byte .srt file.
```
 ✓ The New Heaven Sword & Dragon Sabre - Ep 1: Extract tiff files 
 ]▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇[ 100%   - 1/1 - tif to text files 
 ✓ The New Heaven Sword & Dragon Sabre - Ep 1: Convert text files in srt 
```

**Comment by Jocker666z** [comment]
add this change -> https://github.com/Jocker666z/ffmes/commit/88ced521a0731d74e8f8bca72e9e752999c0b4f6

It is now possible to choose the index.
The limitation is in batch mode, so as not to disturb the user all the time, the choice of index is made on the first file in the list. You therefore need to ensure that all the files in the batch have the same index.
This update is a first draft, I'll improve it when I have a bit more time.

**Comment by glu8716** [comment]
Thanks! I'm trying it now. The id recognition seems to work fine, it's now extracting tiff from english subs correctly. The process seems to be really slow if compared to what it used to be in the past though. Don't know if it's a bad perception of me or if there's something wrong going on

**Comment by Jocker666z** [comment]
> The process seems to be really slow if compared to what it used to be in the past though

I change anything in process. ;)

**Comment by Jocker666z** [comment]
close with commits:
https://github.com/Jocker666z/ffmes/commit/88ced521a0731d74e8f8bca72e9e752999c0b4f6
https://github.com/Jocker666z/ffmes/commit/2ed4552266c18ef1fb35cadf45bdfc0b72ae7921

**Comment by glu8716** [comment]
Unfortunately I still got a 0 byte srt file after completing the process :(
Do you mind trying on your machine with the same subtitle I've given?

**Comment by Jocker666z** [comment]
> Unfortunately I still got a 0 byte srt file after completing the process :( Do you mind trying on your machine with the same subtitle I've given?

It's subptools (app for convert text into srt) bug, when he have "&" in filename crash.

I'll be doing a bypass in ffmes shortly.
But in the meantime you can change the files names like this:
* The New Heaven Sword & Dragon Sabre - Ep 1.idx -> The New Heaven Sword and Dragon Sabre - Ep 1.idx
* The New Heaven Sword & Dragon Sabre - Ep 1.sub -> The New Heaven Sword and Dragon Sabre - Ep 1.sub

**Comment by Jocker666z** [comment]
Close with commit: https://github.com/Jocker666z/ffmes/commit/8983b6e57d5b12e5104e7c066d0f5980a1bdfb43
